### PR TITLE
restore archive now asks for target instead of job.

### LINKED ISSUE #82: `shield restore archive` filtering bug
When restoring archives, the shield CLI attempts to filter the archives presented to the user based on the job selected. This filtering appears to be slightly broken:

```
$ shield restore archive
More than one job matched your search for '':

      Name              Summary                      Target            Store   Schedule
      ====              =======                      ======            =====   ========
   1) redis-dedicated   dedicated-vm redis backups   redis-dedicated   s3      hourly at :22
   2) redis-shared      Shared-vm redis backups      redis-shared      s3      hourly at :22


  Which backup job do you want? [1-2] 2


Here are the 4 most recent backup archives for redis-shared:

      UUID                                   Taken at                          Expires at                        Status   Notes
      ====                                   ========                          ==========                        ======   =====
   1) d73925a8-2bf2-4af9-a5b0-3c80cc4d3544   Tue, 02 Feb 2016 22:32:55 +0000   Wed, 03 Feb 2016 22:32:55 +0000   valid
   2) 97f5ddf4-73aa-4604-af3a-7200699b396e   Tue, 02 Feb 2016 22:32:43 +0000   Wed, 03 Feb 2016 22:32:43 +0000   valid
   3) 8106a4ab-6606-4826-b14b-3e1426c2fd28   Tue, 02 Feb 2016 22:22:03 +0000   Wed, 03 Feb 2016 22:22:03 +0000   valid
   4) f53db303-5767-4eb9-876d-482683e0c10b   Tue, 02 Feb 2016 22:22:03 +0000   Wed, 03 Feb 2016 22:22:03 +0000   valid


  Which backup archive would you like to restore? [1-4] 2


Scheduled immediate restore of archive '97f5ddf4-73aa-4604-af3a-7200699b396e'
```

This shows 4 backups for `redis-shared`. However 2 are for `redis-shared` and 2 are for `redis-dedicated`:
```
$ shield list archives
UUID                                   Target                           Remote IP          Store     Taken at                          Expires at                        Status   Notes
====                                   ======                           =========          =====     ========                          ==========                        ======   =====
d73925a8-2bf2-4af9-a5b0-3c80cc4d3544   redis-dedicated (redis-broker)   10.244.3.54:5444   s3 (s3)   Tue, 02 Feb 2016 22:32:55 +0000   Wed, 03 Feb 2016 22:32:55 +0000   valid
97f5ddf4-73aa-4604-af3a-7200699b396e   redis-shared (redis-broker)      10.244.3.46:5444   s3 (s3)   Tue, 02 Feb 2016 22:32:43 +0000   Wed, 03 Feb 2016 22:32:43 +0000   valid
8106a4ab-6606-4826-b14b-3e1426c2fd28   redis-shared (redis-broker)      10.244.3.46:5444   s3 (s3)   Tue, 02 Feb 2016 22:22:03 +0000   Wed, 03 Feb 2016 22:22:03 +0000   valid
f53db303-5767-4eb9-876d-482683e0c10b   redis-dedicated (redis-broker)   10.244.3.54:5444   s3 (s3)   Tue, 02 Feb 2016 22:22:03 +0000   Wed, 03 Feb 2016 22:22:03 +0000   valid
```

### PR DESCRIPTION
**Pull request by thomasmmitchell**
This happens to fix #82.

Also, fixed comment for how to make config for s3 plugin.
Also, fixes a recent bug where archives could not be listed because of a mis-ordering of arguments in the sql query.

### CODE REVIEW

File: db/archives.go [hunk 1]
```diff
@@ -82,6 +77,12 @@ func (f *ArchiveFilter) Query() string {
 		wheres = append(wheres, fmt.Sprintf("expires_at < $%d", n))
 		n++
 	}
+	limit := ""
+	if f.Limit != "" {
+		limit = fmt.Sprintf(" LIMIT $%d", n)
+		n++
+	}
+
```
Comment (geofffranks) [inline db/archives.go]: Can you add an associated test for this, to prevent it from breaking in the future? Probably something using all the filters + limit. Also a comment on the limit block indicating why it must be last

**Comment by geofffranks** [comment]
Also this branch has conflicts that will need resolution before merging
